package mybot;

public enum IAState {
	// SIMPLE STATE
	HEADQUARTERS(0),
	BARRACKS(1),
	MILL(2),
	MINE(3),
	SPEARMAN(4),
	CROSSBOWMAN(5),
	INQUISITOR(6),
	KNIGHT(7),
	PRIEST(8),
	GOLD(9),
	FOOD(10),
	POP(11),
	MAXPOP(12),
	TOWER(13),
	UNIVERSITY(14),
	// COMPLICATED STATE
	FREESPEARMAN(15),
	FREECROSSBOWMAN(16),
	FREEINQUISITOR(17),
	FREEKNIGHT(18),
	FREEPRIEST(19),
	FREEBARRACK(20),
	FREESTABLE(21),
	STABLES(22),
	
	//LIFEPOINTS
	ATTACKEDHEADQUARTERS(23),
	ATTACKEDBARRACK(24),
	ATTACKEDMILL(25),
	ATTACKEDMINE(26),
	ATTACKEDSTABLES(27),
	ATTACKEDUNIVERSITY(28),
	ATTACKEDTOWER(29),
	ATTACKEDSPEARMAN(30),
	ATTACKEDCROSSBOWMAN(31),
	ATTACKEDKNIGHT(32),
	ATTACKEDINQUISITOR(33),
	ATTACKEDPRIEST(34),
	
	//ENNEMY
	//LIFEPOINTS
	VISIBLEHEADQUARTERS(35),
	VISIBLEBARRACK(36),
	VISIBLEMILL(37),
	VISIBLEMINE(38),
	VISIBLESTABLES(39),
	VISIBLEUNIVERSITY(40),
	VISIBLETOWER(41),
	VISIBLESPEARMAN(42),
	VISIBLECROSSBOWMAN(43),
	VISIBLEKNIGHT(44),
	VISIBLEINQUISITOR(45),
	VISIBLEPRIEST(46);

	public int value;
	private IAState(int value){
		this.value = value;
	}

	public IAState get(int i){
		return values()[i];
	}
	
	public static int size(){
		return values().length;
	}

}
